### ISSUE TITLE
C4324 and C4316 /W4 warnings with MSVC

### ISSUE THREAD

**Issue by mojofunk** [cameron314/readerwriterqueue#107]
Hello, I've been using readerwriterqueue in a project for a while now and it has worked well, Thanks a lot.

I recently updated to a recent revision from the master branch (a500a29f) from a much older version and noticed two new warnings when compiling with the MSVC toolchain.

The first is this warning:

`warning C4324: 'RecordQueuePrivate': structure was padded due to alignment specifier`

Which occurs when a member variable is placed before the moodycamel::ReaderWriterQueue in the class definition.

The second is this warning:

`warning C4316: 'RecordQueuePrivate': object allocated on the heap may not be aligned 64`

Which I can fix(AFAICT) by defining member operator new/delete and using an aligned allocator to allocate the memory for the class that has the moodycamel::ReaderWriterQueue as a member.

An example should be accessible here: https://godbolt.org/z/oET7YE

Would you suggest doing anything to address the first warning apart from disabling it? 

Should I be concerned about the second warning and would you suggest addressing it as I have or in some other fashion?

**Comment by cameron314** [comment]
Both of these warnings are normal; the `ReaderWriterQueue` has been modified to be over-aligned to 64-bytes in order to limit *false sharing* (interference with/from other unrelated data coincidentally in the same cacheline). The alignment is merely an optimization and not a requirement, and therefore it is safe to ignore the warnings.

The first warning is purely informative and can generally always be ignored. I believe as of C++17 the compiler is finally able to `new` over-aligned objects, so, the second warning will go away in time.

**Comment by mojofunk** [comment]
OK, thanks for confirming that these warnings shouldn't be a problem.
