### ISSUE TITLE
Why is ReentrantGuard::inSection not atomic?

### ISSUE THREAD

**Issue by StephanDollberg** [cameron314/readerwriterqueue#110]
Why is `ReentrantGuard::inSection` not atomic (or rather the actual members stored in the queue class)? This feels a bit wrong because when two threads are writing to that at the same it is actually a race condition which is the very thing it's supposed to detect.

I know I know it will probably always be fine with a bool in practice but don't see why they can't be atomic to at least make the C++ lawyers happy?

**Comment by cameron314** [comment]
That's a good point. The main reason is that it's never supposed to be accessed concurrently. It was designed to detect re-entrant accesses, but since (much more frequently-encountered) illegal concurrent accesses also happen to trigger it most of the time, the error message was updated to reflect this.

**Comment by cameron314** [comment]
Fixed :-)
