### ISSUE TITLE
Missing member functions in Android Studio

### ISSUE THREAD

**Issue by svenoaks** [cameron314/readerwriterqueue#115]
In my project using Android Studio 4.1.2 and the inbuilt NDK and the cmake build system, the compiler is not generating all of the template functions for ReaderWriterQueue, most importantly, emplace / try_emplace. Even after invalidating / cleaning / rebuilding everything the problem remains.  

> error: no member named 'emplace' in 'moodycamel::ReaderWriterQueue<float, 512>'

Unfortunately,  I'm unable to reproduce this with a new minimal test project (even with all the same compiler flags), all of the member functions are available then. On the other hand, I don't have this problem with any other classes in my project, all of the template functions are present.

I've tried making sure MOODYCAMEL_HAS_EMPLACE is always defined. 

Here are some screenshots of the functions that are available in my real project vs. test project.

Any ideas what could be causing that?
<img width="393" alt="Screen Shot 2021-03-08 at 1 08 07 PM" src="https://user-images.githubusercontent.com/5206058/110364023-48da5680-8011-11eb-8041-5492014890a1.png">

<img width="581" alt="Screen Shot 2021-03-08 at 12 55 59 PM" src="https://user-images.githubusercontent.com/5206058/110364020-4841c000-8011-11eb-9a93-1ce013ce3ccf.png">

**Comment by cameron314** [comment]
Weird. `MOODYCAMEL_HAS_EMPLACE` should only ever be off for older MSVC versions, which is a completely different platform than the one you're on.

Apparently recent versions of Android Studio support intellisense based on `clangd`: https://developer.android.com/studio/releases#4.0-clangd-clang-tidy

Switching to `clangd`, if possible, should fix this. Apart from that, I don't have any useful suggestions, since I'm entirely unfamiliar with Android Studio.

**Comment by svenoaks** [comment]
I figured out I had a really old version of readerwriterqueue.h in my include path that was found first, which didn't have those functions yet. Sorry for wasting your time!
