### ISSUE TITLE
TSAN warnings on Clang12.

### ISSUE THREAD

**Issue by improbablejan** [cameron314/readerwriterqueue#116]
Hi,

We are using `ReaderWriterQueue` in one of our projects, and have noticed TSAN warnings being reported from or due to the usage of the queue. I made the following small repro:
```
#include "readerwriterqueue.h"
#include <cstddef>
#include <memory>
#include <thread>

int main() {
  constexpr static std::size_t kElements = 1000;
  moodycamel::ReaderWriterQueue<std::shared_ptr<std::size_t>> q;

  std::thread t{[&q] {
    std::shared_ptr<std::size_t> out;
    for (std::size_t i = 0; i < kElements; ++i) {
      while (!q.try_dequeue(out)) {
        *out;
      }
    }
  }};

  for (std::size_t i = 0; i < kElements; ++i) {
    q.enqueue(std::make_shared<std::size_t>(i));
  }
  t.join();

  return 0;
}
```
Running `clang++-12 --std=c++17 tsan_warnings.cc -lpthread -fsanitize=thread -g && ./a.out 2&> tsan_report.log` produces [tsan_report.log](https://github.com/cameron314/readerwriterqueue/files/6124247/tsan_report.log).

When the queue holds `std::size_t` rather than `std::shared_ptr<std::size_t>` the number of warnings goes down to 3. What's particularly unpleasant about this issue is that we cannot easily suppress all the warnings, since not all warnings have `readerwriterqueue.h` in at least one of the stack traces.

Is our usage of the queue correct? I found https://github.com/cameron314/readerwriterqueue/issues/65 which seems to suggest a similar usage (as far as I understood it) using a `std::string` is legal. Is this indicative of an actual issue, or a false positive? Is there something that could be done to prevent these warnings from cropping up?

Version information:
```
$ clang++-12 --version
Ubuntu clang version 12.0.0-++20210303094403+9760b282ff03-1~exp1~20210303205143.53
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```
I used `readerwriterqueue.h` and `atomicops.h` from the v1.0.4 tag, though we have originally observed this in version 1.0.2. This is new code, I do not know whether or not this worked previously without warnings.

Thanks for taking a look!
Best,
Jan

**Comment by cameron314** [comment]
I'll have to take a closer look at this specific example, but it's important to note that in general, tsan can give false positives and is not very good at handling lock-free code.

**Comment by cameron314** [comment]
Your example code is correct, at least :-)

**Comment by russellmcc** [comment]
First, thanks so much for this library.

This was bothering me as well.  I believe I tracked down the cause of the false positives to the fact that thread sanitizer [has no support for `atomic_thread_fence`](https://github.com/google/sanitizers/issues/1352) and `readerwriterqueue` relies entirely on `atomic_thread_fence` for synchronization.  So, thread sanitizer doesn't work well on `readerwriterqueue` and gives a lot of false positives.

I don't have any good answers here, unfortunately.

One question I have is, is there any strong reason for the library to use `atomic_thread_fence` rather than acquire and release operations?  Was this simply the author's preference or was there some technical constraint that prevented the use of acquire and release operations?  If there are no blockers, one potential way to appease the thread sanitizer would be to move to acquire and release operations, although of course this would be a huge, expensive shift.

While poking around, I found something that does appear to work, although I frankly don't understand why it does work.  Annotating the `atomic_thread_fence` operations with thread sanitizer acquire and release annotations for an unrelated global variable seems to make thread sanitizer correctly understand the fences.  For more information on how fences and acquire and release operations differ, I found [this blog post](https://preshing.com/20131125/acquire-and-release-fences-dont-work-the-way-youd-expect/) quite useful.

I've sketched out this approach on a branch: https://github.com/russellmcc/readerwriterqueue/tree/experimental/tsan-annotate which seems to work well so far in all the cases I've tried, including the example from @improbablejan above and another minimal example I adapted from [this github issue on concurrentqueue](https://github.com/cameron314/concurrentqueue/issues/49#issuecomment-222753780)

```
#include "readerwriterqueue.h"
#include <thread>

struct task
{
    int x = 0;

    task() {}
    task(int x_) : x{x_} {}
    task(const task &) = delete;
    task &operator=(const task &) = delete;

    task(const task &&rhs) : x{rhs.x}
    {
    }

    task &operator=(const task &&rhs)
    {
        x = rhs.x;
        return *this;
    }
};

// task queue
moodycamel::ReaderWriterQueue<task> q;

int main()
{
    std::thread th([&]() {
        task t;
        for (int i = 0; i != 1000; ++i)
            q.try_dequeue(t);
    });

    for (int i = 0; i < 1000; ++i)
        q.enqueue(task{i});

    th.join();
}
```

Anyways, looking forward to any guidance you have on how to proceed.  While it's uncomfortable to rely on undocumented behavior in tsan as in my branch, this problem is pretty annoying and it would be great to solve it somehow.

**Comment by cameron314** [comment]
> One question I have is, is there any strong reason for the library to use atomic_thread_fence rather than acquire and release operations? Was this simply the author's preference or was there some technical constraint that prevented the use of acquire and release operations? If there are no blockers, one potential way to appease the thread sanitizer would be to move to acquire and release operations, although of course this would be a huge, expensive shift.

Yes, at the time this was written, I wanted to support VS2010, which did not support `<atomic>` (but did provide platform-specific ways of emitting barriers). For obvious reasons, I would prefer not to rewrite all the code to exclusively rely on C++11 operations at this point. In my experience, `tsan` is not much better at avoiding false-positives with low-level atomics in any case.

I'll have a look at your branch.

**Comment by cameron314** [comment]
@russellmcc, I like the approach taken by your branch (forcing `tsan` synchronization using a single global variable). Thanks for that! I've adapted it into my master branch; the main difference is I kept `AE_NO_TSAN` for the non-C++17 case.

Hopefully this is sufficient for most use cases. Please re-open if `tsan` warnings persist.

**Comment by improbablejan** [comment]
Thanks both, I just picked this up and was able to delete tsan suppressions for readerwriterqueue :tada:
