### ISSUE TITLE
Possible concurrency issue in queue when used in reader and writer pthreads

### ISSUE THREAD

**Issue by virgoptrex** [cameron314/readerwriterqueue#13]
I conducted some further tests and found an interesting tidbit in my C++ code. I used two pthreads (one reader and one writer) to transfer some data with the lock free queue object declared global. When I run both pthreads and there is *NO* millisleep function in writer thread between each write (or reader thread), everything works fine! I am able to read data correctly in the reader thread. Then I introduce a millisleep 100 ms in writer thread between each writes and the reader is NOT able to read the data anymore. Any idea why? Have you conducted such a test? I would think declaring global queue should not be a problem (it is extern but should not be a problem).

Run the following code by changing _DELAY_ macro to 0 or 1. No delay behaviour seems odd. Disqus screwed my indentation so use some program like 'astyle' to get it back.

//===================== code starts below ========================

//Quick and dirty test by virgoptrex for Cameron's MoodyCamel Lock Free Queue
//compile using: g++ -g pthread_test.cc -o pthread_test -lpthread -std=c++0x

//Change _DELAY_ value to 1 and 0 to toggle between delay and no delay

#define __STDC_FORMAT_MACROS
#include <inttypes.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include "readerwriterqueue.h"

#ifndef _DELAY_
#define _DELAY_ 1
#endif

moodycamel::ReaderWriterQueue<uint64_t> queue;

void milliseconds_delay(uint32_t milisec)
{
    struct timespec req = {0};
    req.tv_sec = 0;
    req.tv_nsec = milisec * 1000000L;
    nanosleep(&req, (struct timespec *)NULL);
}

void *Writer(void *threadid)
{
    long tid;
    uint64_t counter = 0;
    tid = (long)threadid;
    printf("Hello World! It's me, thread #%ld!\n", tid);
    while(1) {
        queue.try_enqueue(counter++);
        printf("sent uint64_t : %" PRIu64 "\n", counter);
#if _DELAY_
        milliseconds_delay(100);
#endif
    }
    pthread_exit(NULL);
}

void *Reader(void *threadid)
{
    long tid;
    tid = (long)threadid;
    printf("Hello World! It's me, thread #%ld!\n", tid);
    while(1) {
        uint64_t value;
        queue.try_dequeue(value);
        printf("received uint64_t : %" PRIu64 "\n", value);
#if _DELAY_
        milliseconds_delay(100);
#endif
    }
    pthread_exit(NULL);
}

int main (int argc, char *argv[])
{
    pthread_t reader_thread;
    pthread_t writer_thread;
    int rc;
    long t;
    printf("In main: creating reader thread %ld\n", t);
    rc = pthread_create(&reader_thread, NULL, Reader, (void *)0);
    if (rc) {
        printf("ERROR; return code from reader pthread_create() is %d\n", rc);
        exit(-1);
    }
    printf("In main: creating thread %ld\n", t);
    rc = pthread_create(&writer_thread, NULL, Writer, (void *)1);
    if (rc) {
        printf("ERROR; return code from writer pthread_create() is %d\n", rc);
        exit(-1);
    }
    // Last thing that main() should do 
    pthread_exit(NULL);
}

**Comment by virgoptrex** [comment]
I added if condition around queue and dequeue now seems okay. I want to check what happens when reader is the main thread loop and writer is the only pthread.

//===================== code starts below ========================

//Quick and dirty test by virgoptrex for Cameron's MoodyCamel Lock Free Queue
//compile using: g++ -g pthread_test.cc -o pthread_test -lpthread -std=c++0x

//Change _DELAY_ value to 1 and 0 to toggle between delay and no delay

#define __STDC_FORMAT_MACROS
#include <inttypes.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include "readerwriterqueue.h"

#ifndef _DELAY_
#define _DELAY_ 0 
#endif

moodycamel::ReaderWriterQueue<uint64_t> queue;

void milliseconds_delay(uint32_t milisec)
{
    struct timespec req = {0};
    req.tv_sec = 0;
    req.tv_nsec = milisec * 1000000L;
    nanosleep(&req, (struct timespec *)NULL);
}

void *Reader(void *threadid)
{
    long tid;
    uint64_t counter = 0;
    tid = (long)threadid;
    printf("Hello World! It's me, thread #%ld!\n", tid);
    while(1) {
        if(queue.try_enqueue(counter++))
        printf("sent uint64_t : %" PRIu64 "\n", counter);
#if _DELAY_
        milliseconds_delay(100);
#endif
    }
    pthread_exit(NULL);
}

void *Writer(void *threadid)
{
    long tid;
    tid = (long)threadid;
    printf("Hello World! It's me, thread #%ld!\n", tid);
    while(1) {
        uint64_t value;
        if(queue.try_dequeue(value))
        printf("received uint64_t : %" PRIu64 "\n", value);
#if _DELAY_
        milliseconds_delay(100);
#endif
    }
    pthread_exit(NULL);
}

int main (int argc, char *argv[])
{
    pthread_t reader_thread;
    pthread_t writer_thread;
    int rc;
    long t;
    printf("In main: creating reader thread %ld\n", t);
    rc = pthread_create(&reader_thread, NULL, Reader, (void *)0);
    if (rc) {
        printf("ERROR; return code from reader pthread_create() is %d\n", rc);
        exit(-1);
    }
    printf("In main: creating thread %ld\n", t);
    rc = pthread_create(&writer_thread, NULL, Writer, (void *)1);
    if (rc) {
        printf("ERROR; return code from writer pthread_create() is %d\n", rc);
        exit(-1);
    }

    /* Last thing that main() should do */
    pthread_exit(NULL);
}

**Comment by cameron314** [comment]
Thanks for opening an issue! Don't worry about the formatting, it's a short enough example that it doesn't matter much.

If I understand you correctly, you had trouble using `try_dequeue` without the `if`, and then turning it into `if(queue.try_dequeue(value))` fixed the problem. Is this right?

If so, then that actually makes sense, though it's unfortunate the compiler doesn't emit a warning in such a case -- what happens is that the `value` parameter is only written to when there is something to dequeue; if the queue appears empty when you call `try_dequeue`, the `value` variable is never initialized, leading to undefined behaviour when it's used afterwards. (I've personally seen this exact bug in some of my own code lead to seemingly-impossible behaviour (in single threaded code), though that was with VC++2013.)

If this is the case, changing the first version to initialize `value` to something before calling `try_dequeue` (and leaving out the `if`) should also stop the weird behaviour (though of course your real code would probably want to use the `if`, and so wouldn't need to initialize the variable).

Another thing I've noticed in the sample code is that you're calling `try_enqueue` (in the writer) instead of `enqueue`. Perhaps that is intended, but just in case you're not aware, `try_enqueue` will fail if there's not enough room in the queue, and since you don't pass in an initial minimum size to the constructor, the default queue size is only 15 elements at a time.

And because I'm so slow at responding you've closed the issue before I finished my long comment ^_^ No worries!

**Comment by virgoptrex** [comment]
Thanks for response Cameron. 

"If I understand you correctly, you had trouble using try_dequeue without the if, and then turning it into if(queue.try_dequeue(value)) fixed the problem. Is this right?" -> Yes

"If this is the case, changing the first version to initialize value". Well yes in this example it is very easy to init but my object in the actual code is multilevel nested "protocol buffer"(RPC) object rather than a simple primitive (technically still not a primitive like 'int' or 'char') like uint64_t. I think I will have to init all nested levels. The form of the object in pseudo code is like "message A{ message B {message C; message D;}}}. If you google protobuf it should tell you more information.

"Perhaps that is intended, but just in case you're not aware, try_enqueue will fail if there's not enough room in the queue, and since you don't pass in an initial minimum size to the constructor". -> Maybe ?I should use enqueue then. I have used a wrappers around your function like 

//Lock Free Queue
template< typename T >
inline bool WriteToLockFreeQueue(moodycamel::ReaderWriterQueue<T> &queue, T data){
    return (queue.try_enqueue(data)); //return success or failure
}

template< typename T >
inline bool ReadFromLockFreeQueue(moodycamel::ReaderWriterQueue<T> &queue, T& data){
   return  (queue.try_dequeue(data)); //return success or failure
}

template< typename T >
inline bool IsLockFreeQueueEmpty(moodycamel::ReaderWriterQueue<T> &queue){
   return  (queue.peek()==nullptr?true:false);
}

template< typename T >
inline T PeekFrontLockFreeQueue(moodycamel::ReaderWriterQueue<T> &queue){
   if(IsEmpty(queue)){     
       throw "Not a valid object";
   }
   return  *(queue.peek());
}

Let me know what you think of these wrappers. Perhaps change try_enqueue to enqueue?

I think I misunderstood the use of APIs, until I started digging more into the documentation.

**Comment by cameron314** [comment]
Sorry, I wasn't very clear -- you don't need to initialize the variable before passing it to `try_dequeue`, as long as you only use that variable's value if the call succeeded (returned true), otherwise it will be uninitialized. So the "Read" part of your wrapper seems fine.

In fact, your entire wrapper seems fine (except that moodycamel::ReaderWriterQueue is missing the template parameter, but I suspect that's just a formatting problem -- just FYI, you can indent the code four spaces/one tab to have it displayed better on github).

The only thing I would change is `try_enqueue` to `enqueue`. The purpose of `try_enqueue` is when you want to avoid memory allocation during an enqueue operation (i.e. the queue is treated as fixed in size). This is generally only used in combination with an explicit initial size argument to the constructor.

`enqueue` works the same way, except that it can allocate memory to make the queue bigger if it's currently full (and thus it always succeeds in enqueueing the element unless memory allocation itself fails). That's probably what you want in a general wrapper like this.

Also note that your peek wrapper is returning a copy of the object instead of a reference. This may be on purpose, of course.

Finally, If you're after every last ounce of performance, I would also change your peek wrapper to call `queue.peek()` only once, instead of twice (once through `IsEmpty()` and once in the body of the function). Again, you may have designed it this way on purpose (for clearer code). It's up to you! :-)

**Comment by virgoptrex** [comment]
Awesome thanks for the feedback!
