### ISSUE TITLE
Free memory on clear() and shrinking

### ISSUE THREAD

**Issue by mdimura** [cameron314/readerwriterqueue#20]
At the moment the queue can only increase its memory consumption. Would it be possible to release allocated memory when the size() decreases or when clear() is called?

**Comment by cameron314** [comment]
This is unfortunately impossible to do under concurrency. I could conceivably add a `clear()` function that would do this, but it would be up to the user to call it only when the queue is not being accessed by another thread. I really don't want to do this, though, because it will almost certainly eventually be called under concurrency by mistake.

I could add a move constructor/assignment operator, though. You would then be able to move-assign a temporary (empty) queue into the other in order to effectively clear it. Again, it would not be thread-safe to do this, but at least it would be obvious that it's not thread-safe.

**Comment by Burning-Daylight** [comment]
The second option sounds good to me. One could also add clear_nonconcurrent() or clear_singlethread() method for clarity. shrink_singlethread() could also be useful.

**Comment by cameron314** [comment]
As of this writing, a move-assignment operator exists.
