### ISSUE TITLE
Feature request: add capacity() method

### ISSUE THREAD

**Issue by neomantra** [cameron314/readerwriterqueue#22]
Expose a method which calculates the number of items that can be pushed on an empty queue without allocation.

This is useful for tuning purposes -- e.g. upon destruction one can compare initial to final queue capacities.

**Comment by cameron314** [comment]
Good idea. Might take me a little while to get around to it, though (sorry!).

**Comment by neomantra** [comment]
I think the implementation might look like this?   Let me know what you think and I'll incorporate it, write tests, and give you a PR.

```C++
// Returns the total number of items that could be enqueued
// upon an empty queue without incurring an allocation.
inline size_t capacity() const {
    size_t result = 0;
    Block* frontBlock_ = frontBlock.load();
    Block* block = frontBlock_;
    do {
        fence(memory_order_acquire);
        result += (block->sizeMask + 1);
        block = block->next.load();
    } while (block != frontBlock_);
    return result;
}
```

**Comment by cameron314** [comment]
Pull requests with tests are always welcome!

Your implementation looks good to me, except that the number of items that can be enqueued to each block is actually one less than its size, since it wastes a slot to avoid ambiguity between empty and full (it's using head/tail indices instead of a count). So the `+=` should actually only be of `block->sizeMask`, without the `+ 1`. Even simpler! ;-)

I would also tweak the documentation to note that the actual capacity during usage may be different depending on the consumer (if the consumer is removing elements concurrently, the producer cannot add to the block the consumer is removing from until it's completely empty). See the code for in the constructor (especially the comments) starting at [line 80](https://github.com/cameron314/readerwriterqueue/blob/master/readerwriterqueue.h#L80) -- it calculates the opposite, a minimum capacity from a desired capacity. Actually, in light of this, perhaps a better name for your method would be `max_capacity()` (i.e. if there is no consumer involved). `min_capacity()` would be the same except without the largest block (unless there's only one block, in which case it's that block).

**Comment by rahulzbali** [comment]
void moodycamel::BlockingReaderWriterQueue<T, MAX_BLOCK_SIZE>::wait_dequeue(U&) [with U = std::shared_ptr<QX::TradingCore::StrategyOrderEvent>; T = std::shared_ptr<QX::TradingCore::StrategyOrderEvent>; long unsigned int MAX_BLOCK_SIZE = 512ul]: Assertion `success' failed.

can you help about these
