### ISSUE TITLE
Use std::vector as Type in the readerwriterqueue

### ISSUE THREAD

**Issue by FramusRock** [cameron314/readerwriterqueue#27]
Hey,

Is it possible to use std::vector as a type of the queue?
I guess not, since the queue is allocating memory depending on the type and it probably can't know how big the vectors will be.

In case you wonder, I'm trying to solve the following problem with your queue:

Thread A writes data in chunks (this would be my vector) and once it's done with a chunk
Thread B is allowed to read a chunk

The problem is that Thread A's chunks are of variable size and Thread B shall only read a chunk once Thread A is done with a whole chunk.

That's why I'd like to insert std::vector into the queue.

**Comment by cameron314** [comment]
Absolutely. The queue works with any C++ object type (with the caveat that the objects must not throw an exception from their copy constructor nor copy assignment operator, unless they're movable in which case they are moved and not copied at all). You should be able to pass around `std::vector`s without any problem.

This works because the queue only needs to allocate space for the vector object itself, and not all its contents (the vector object already takes care of that itself -- its contents are not stored within it, but on the heap).
