### ISSUE TITLE
Bound on size_approx()

### ISSUE THREAD

**Issue by svenoaks** [cameron314/readerwriterqueue#35]
Is there a bound on how bad the approximation will be?

What I really want to do is operate with two different max sizes for the queue under two different conditions (running in background on Android needs a bigger queue, but a big queue adds a lot of latency when in foreground). I don't really want to switch to a different queue because it will cause a break in the audio. Is there way I can achieve this with size_approx(), or is calling that frequently going to severely impact performance?

Also, I'd love to run the tests on ARM, is there a single call I can do to do this, I haven't really looked through the files yet.

**Comment by cameron314** [comment]
Interesting question!

There is no theoretical bound on the error of the returned value from `size_approx`. This is because it is reading a potentially quite stale value from the other thread which may have updated it several times before the CPU caching subsystem propagates those changes to the core calling `size_approx()`. However, the error will always be due to the other thread's variable being out of date (the current one will be exact). This means that if you call `size_approx()` from the producer thread, the value returned may be greater than the number of elements actually in the queue, but never smaller. In that way, you can achieve a lower bound.

`size_approx()` is O(n) with the number of blocks in the queue. So if you use a pre-allocated queue and don't add more elements than that, `size_approx()` is actually very fast (a few reads, chasing a couple pointers that can be predicted, and a few predictable branches). So you could call this instead of relying on `try_enqueue()`, since you know it will give you a lower bound on the number of elements in the queue. However, depending on the hardware (every CPU caching system is different), the value returned by `size_approx` may not update very frequently (think of a step function), leading to the need to buffer more audio anyway.

Instead, I suggest using a single additional atomic variable shared between the producer and consumer (yes, this will add a little overhead, but not much), say `std::atomic<unsigned> size`. Then, just *before* enqueueing an element, do `size.fetch_add(1, std::memory_order_relaxed);`. Just *after* dequeueing an element, do `size.fetch_add(-1, std::memory_order_relaxed)`. Just as before, when you read `size` on the producer thread (with `size.load(std::memory_order_relaxed)`), it will give you a lower bound on the number of elements actually in the queue. The difference is that it is guaranteed to be updated every time you enqueue an element. (Alternatively, you could force it to be updated every time you read it via `size.fetch_add(0, std::memory_order_relaxed)`, but this is more costly.)

As for ARM, I've never tried. I can't recall if others have either. Regardless, you should be able to simply go into the `tests/stabtest` and `test/unittests` folders and execute `make run` to build and run the respective tests.

**Comment by svenoaks** [comment]
Thanks, your idea worked well. I assume using the default memory_order
would result in performance degradation, that's why there can't be a true
size variable known to both threads?

**Comment by cameron314** [comment]
Nah, you could use the default `std::memory_order_seq_cst` for the increments, it would come to exactly the same performance (since the nature of the operation is an atomic read-modify-write, it has to coordinate with the other cores to get the most recent value anyway). I just default to `memory_order_relaxed` unless otherwise necessary :-)

But come to think of it, they should both be at least `memory_order_acq_rel` otherwise the compiler is free to reorder them improperly in this case (losing your minimum guarantee).

In any case, there can never really be an accurate `size` since there's always a race between the time you read its value and the time that you take an action based on that (at which point, it may already have changed).
