### ISSUE TITLE
Insert a readerwriterqueue into a map

### ISSUE THREAD

**Issue by nchiarappa** [cameron314/readerwriterqueue#57]
Hi!
First of all, great work! I'm trying to insert a readerwriterqueue into a map but the 

ReaderWriterQueue(ReaderWriterQueue const&) {} 

method is private. Here is what I'm trying to do:

`std::unordered_map<uint32_t, ReaderWriterQueue<int>> map;`
`ReaderWriterQueue<int> rwq(10000);`
`rwq.enqueue(10);`
`map.insert(std::pair<uint32_t, ReaderWriterQueue<int>>(1,rwq));`

Do you know how can this be solved?
Moreover, why disable copying?
Thank you!

**Comment by cameron314** [comment]
The queue can't be copied safely under contention. Since there's no way to determine if the copy is occurring under contention or not, and copies are easy to accidentally make in C++, copying is disabled.

However, moving is still allowed:
    map.insert(std::pair<uint32_t, ReaderWriterQueue<int>>(1,std::move(rwq)));

This can be further simplified using `std::make_pair` to deduce the template types:
    map.insert(std::make_pair(1u, std::move(rwq)));

Or even more simply using `emplace`:
    map.emplace(1, std::move(rwq));

**Comment by nchiarappa** [comment]
Thanks for the fast answer!
I used shared pointers in the map as values and it works well now. :)
