### ISSUE TITLE
uneven execution time for the function : try_dequeue()

### ISSUE THREAD

**Issue by asadmshah3** [cameron314/readerwriterqueue#64]
below are the performance execution time for the call try_dequeue () (time in microsecond for performance measurement) 

0.8
0.9
0.8
0.9
1.0
0.9
5.7
5.6
12.0
6.0
7.6
5.4
1.0
1.0
1.0
0.9
0.9
0.5
1.7
2.5
8.48
11.63
0.9
0.7
0.6
0.5
9.9
0.9
1.4
0.9

Above stats shows that in a cyclic faction the execution time varies. Also, the variation is too much i.e. approx 10 times. what might could be the cause ? I am not able to figure it out.

**Comment by cameron314** [comment]
Several potential causes. Is this all on the same thread? Is this with or without a consumer token? Does your object type allocate memory when it is move-assigned?

**Comment by asadmshah3** [comment]
thanks , kindly see my answers ...
- 2 different threads, I'm doing try_enqueue() in 1 thread and another thread is doing try_dequeue()
- its a single producer , single consumer 
- just doing enque of pointer to network packets , not allocating memory 

I am also interested in knowing that Does OS do any kind of preemption even in case of using the memory barrier (used to exchanged data b/w 2 threads in a Queue). If Yes, is there any approach to use speculative reading ? 
Is there any documentation on internal working and implementation ? Thank you

**Comment by cameron314** [comment]
Ok! That narrows down the potential causes of latency a lot. Off the top of my head, here's what might be happening, in roughly descending order of likelihood:
- try_dequeue takes different amounts of time depending on if the queue is empty or not. Tag each timing with whether the call succeeded or not to see if this is why.
- Your timing code may not be giving you precise enough measurements. Check for this by calling a known-constant-time non-inlined function instead of try_dequeue, e.g. clock(), exp(argc, argc), or maybe even rand(), and see if you still have jitter. I put this as fairly likely since the measurements should not be in the whole microsecond range in general.
- The queue makes use of cached values to determine what to do. If the queue has 500 things in it, the first dequeue will read the shared variable so that it knows there's 500 things, but the next dequeue will remember that there's 499 left and does not have to reread any shared values except the element itself (since doing so can be expensive at the hardware level). If you see a pattern between the queue becoming empty, then non-empty and the next dequeue taking longer, but then the next few subsequent ones (where the queue is still non-empty) being faster, this is why.
- The jitter may be at the hardware level; each time a shared variable is read from one core after being written on another, the cache subsystem needs to resolve the latest value from the cache of the other core. This can be relatively expensive, and may be a variable amount of time depending on if the L1 or L2 caches are involved, and how busy the other cores and caching system is. This is hard to detect, but make sure at least that very few other CPU-bound threads are running (less than your total core count).

**Comment by cameron314** [comment]
To answer your other questions, the OS does preemption whenever it wants, and doesn't care about the memory barriers. In fact, if you're on x86, the memory barriers compile down to nothing, since the hardware offers strong guarantees. OS preemption is not in the picture here, though, because your variance would be in the multi-millisecond range, or at least the high microsecond range if there's many threads waking then yielding right away.

Not sure what you're referring to with "speculative reading", but the queue does cache shared values to avoid re-reading them when it doesn't have to (i.e. it has a thread-local cache of a few key values).

**Comment by cameron314** [comment]
Actually, on second thought, there could still be preemption involved, though it would be during the intervals that are not measured, i.e. while all the rest of the code was running. That would pollute the cache and reduce the execution time of the next dequeue. You can check for this by timing the intervals between calls to try_dequeue as well, assuming the rest of the code in between runs in roughly constant time.

It's also possible that the other code that is running is periodically causing the L1 cache to forget about the queue, increasing the latency on the next execution. This can be checked for by not doing anything interesting between the calls :-)

**Comment by asadmshah3** [comment]
Thanks for your answers in detail. Problem didn't replicated on another machine with many cores, so I assume possible cause among those which you mentioned regarding OS preemption and cache thing. Thank you once again :-)
